module.exports = [
  {
    "link": "http://www.datpiff.com/Meek-Mill-Dreamchasers-2-mixtape.339288.html",
    "thumb_image": "http://hw-img.datpiff.com/m201ee08/Meek_Mill_Dreamchasers_2-front.jpg",
    "title": "Dreamchasers 2",
    "artist": "Meek Mill",
    "downloads": 4515700,
    "city": "Philadelphia",
    "state": "Pennsylvania",
    "month": 5,
    "day": 7,
    "year": 2012,
    "analysis": {}
  },
  {
    "link": "http://www.datpiff.com/Lil-Wayne-Sorry-4-The-Wait-mixtape.250654.html",
    "thumb_image": "http://hw-img.datpiff.com/m4749b9f/Lil_Wayne_Sorry_4_The_Wait-front.jpg",
    "title": "Sorry 4 The Wait",
    "artist": "Lil Wayne",
    "downloads": 2881661,
    "city": "New Orleans",
    "state": "Louisiana",
    "month": 7,
    "day": 13,
    "year": 2011,
    "analysis": {}
  },
  {
    "link": "http://www.datpiff.com/Big-Sean-Detroit-mixtape.390127.html",
    "thumb_image": "http://hw-img.datpiff.com/mc76cb91/Big_Sean_Detroit-front.jpg",
    "title": "Detroit",
    "artist": "Big Sean",
    "downloads": 2238047,
    "city": "Detroit",
    "state": "Michigan",
    "month": 9,
    "day": 5,
    "year": 2012,
    "analysis": {}
  },
  {
    "link": "http://www.datpiff.com/Wiz-Khalifa-Taylor-Allderdice-mixtape.324466.html",
    "thumb_image": "http://hw-img.datpiff.com/ma69acab/Wiz_Khalifa_Taylor_Allderdice-front.jpg",
    "title": "Taylor Allderdice",
    "artist": "Wiz Khalifa",
    "downloads": 2224349,
    "city": "Pittsburgh",
    "state": "Pennsylvania",
    "month": 3,
    "day": 13,
    "year": 2012,
    "analysis": {}
  },
  {
    "link": "http://www.datpiff.com/Lil-Wayne-Dedication-4-mixtape.385544.html",
    "thumb_image": "http://hw-img.datpiff.com/m228cceb/Lil_Wayne_Dedication_4-front.jpg",
    "title": "Dedication 4",
    "artist": "Lil Wayne",
    "downloads": 2158412,
    "city": "New Orleans",
    "state": "Louisiana",
    "month": 9,
    "day": 3,
    "year": 2012,
    "analysis": {}
  },
  {
    "link": "http://www.datpiff.com/Rick-Ross-Rich-Forever-mixtape.296828.html",
    "thumb_image": "http://hw-img.datpiff.com/m5a5d7eb/Rick_Ross_Rich_Forever-front.jpg",
    "title": "Rich Forever",
    "artist": "Rick Ross",
    "downloads": 1938981,
    "city": "Carol City",
    "state": "Florida",
    "month": 1,
    "day": 6,
    "year": 2012,
    "analysis": {}
  },
  {
    "link": "http://www.datpiff.com/Wiz-Khalifa-Cabin-Fever-2-mixtape.406664.html",
    "thumb_image": "http://hw-img.datpiff.com/m8a7d560/Wiz_Khalifa_Cabin_Fever_2-front.jpg",
    "title": "Cabin Fever 2",
    "artist": "Wiz Khalifa",
    "downloads": 1848251,
    "city": "Pittsburgh",
    "state": "Pennsylvania",
    "month": 10,
    "day": 16,
    "year": 2012,
    "analysis": {}
  },
  {
    "link": "http://www.datpiff.com/Jadakiss-Consignment-mixtape.340926.html",
    "thumb_image": "http://hw-img.datpiff.com/m2306d62/Jadakiss_Consignment-front.jpg",
    "title": "Consignment",
    "artist": "Jadakiss",
    "downloads": 1799948,
    "city": "Yonkers",
    "state": "New York",
    "month": 4,
    "day": 26,
    "year": 2012,
    "analysis": {}
  },
  {
    "link": "http://www.datpiff.com/ASAP-Rocky-LiveLoveAap-mixtape.278798.html",
    "thumb_image": "http://hw-img.datpiff.com/mc4c9501/ASAP_Rocky_Liveloveaap-front.jpg",
    "title": "LiveLoveA$ap",
    "artist": "A$AP Rocky",
    "downloads": 1671336,
    "city": "Harlem",
    "state": "New York",
    "month": 10,
    "day": 31,
    "year": 2011,
    "analysis": {}
  },
  {
    "link": "http://www.datpiff.com/Wiz-Khalifa-Kush-OJ-mixtape.112367.html",
    "thumb_image": "http://hw-img.datpiff.com/m1aaed3d/Wiz_Khalifa_Kush_OJ-front.jpg",
    "title": "Kush & OJ",
    "artist": "Wiz Khalifa",
    "downloads": 1658597,
    "city": "Pittsburgh",
    "state": "Pennsylvania",
    "month": 4,
    "day": 14,
    "year": 2010,
    "analysis": {}
  },
  {
    "link": "http://www.datpiff.com/Lil-Wayne-No-Ceilings-mixtape.75250.html",
    "thumb_image": "http://hw-img.datpiff.com/mc6d044d/Lil_Wayne_No_Ceilings-front.jpg",
    "title": "No Ceilings",
    "artist": "Lil Wayne",
    "downloads": 1552522,
    "city": "New Orleans",
    "state": "Louisiana",
    "month": 11,
    "day": 1,
    "year": 2009,
    "analysis": {}
  },
  {
    "link": "http://www.datpiff.com/Lil-Wayne-Dedication-5-mixtape.525016.html",
    "thumb_image": "http://hw-img.datpiff.com/m97454a7/Lil_Wayne_Dedication_5-front.jpg",
    "title": "Dedication 5",
    "artist": "Lil Wayne",
    "downloads": 1452185,
    "city": "New Orleans",
    "state": "Louisiana",
    "month": 8,
    "day": 30,
    "year": 2013,
    "analysis": {}
  },
  {
    "link": "http://www.datpiff.com/French-Montana-Mac-Cheese-3-mixtape.392996.html",
    "thumb_image": "http://hw-img.datpiff.com/m61d400b/French_Montana_Mac_Cheese_3-front.jpg",
    "title": "Mac & Cheese 3",
    "artist": "French Montana",
    "downloads": 1430890,
    "city": "Bronx",
    "state": "New York",
    "month": 11,
    "day": 20,
    "year": 2012,
    "analysis": {}
  },
  {
    "link": "http://www.datpiff.com/Drake-So-Far-Gone-mixtape.34130.html",
    "thumb_image": "http://hw-img.datpiff.com/m6660ffe/Drake_So_Far_Gone-front.jpg",
    "title": "So Far Gone",
    "artist": "Drake",
    "downloads": 1353503,
    "city": "Toronto",
    "state": "Ontario",
    "month": 2,
    "day": 13,
    "year": 2009,
    "analysis": {}
  },
  {
    "link": "http://www.datpiff.com/Wiz-Khalifa-Cabin-Fever-mixtape.200862.html",
    "thumb_image": "http://hw-img.datpiff.com/ma0fdf13/Wiz_Khalifa_Cabin_Fever-front.jpg",
    "title": "Cabin Fever",
    "artist": "Wiz Khalifa",
    "downloads": 1345071,
    "city": "Pittsburgh",
    "state": "Pennsylvania",
    "month": 2,
    "day": 17,
    "year": 2011,
    "analysis": {}
  },
  {
    "link": "http://www.datpiff.com/Meek-Mill-Dreamchasers-3-mixtape.439835.html",
    "thumb_image": "http://hw-img.datpiff.com/m8b7009f/Meek_Mill_Dreamchasers_3-front.jpg",
    "title": "Dreamchasers 3",
    "artist": "Meek Mill",
    "downloads": 1291695,
    "city": "Philadelphia",
    "state": "Pennsylvania",
    "month": 9,
    "day": 29,
    "year": 2013,
    "analysis": {}
  },
  {
    "link": "http://www.datpiff.com/Rick-Ross-The-Black-Bar-Mitzvah-mixtape.402975.html",
    "thumb_image": "http://hw-img.datpiff.com/m903e955/Rick_Ross_The_Black_Bar_Mitzvah-front.jpg",
    "title": "The Black Bar Mitzvah",
    "artist": "Rick Ross",
    "downloads": 1255729,
    "city": "Carol City",
    "state": "Florida",
    "month": 10,
    "day": 8,
    "year": 2012,
    "analysis": {}
  },
  {
    "link": "http://www.datpiff.com/Meek-Mill-Dreamchasers-mixtape.256292.html",
    "thumb_image": "http://hw-img.datpiff.com/m1fc13c8/Meek_Mill_Dreamchaser-front.jpg",
    "title": "Dreamchasers",
    "artist": "Meek Mill",
    "downloads": 1239292,
    "city": "Philadelphia",
    "state": "Pennsylvania",
    "month": 8,
    "day": 11,
    "year": 2011,
    "analysis": {}
  },
  {
    "link": "http://www.datpiff.com/Wiz-Khalifa-28-Grams-mixtape.613330.html",
    "thumb_image": "http://hw-img.datpiff.com/m95e3fe1/Wiz_Khalifa_28_Grams-front.jpg",
    "title": "28 Grams",
    "artist": "Wiz Khalifa",
    "downloads": 1231379,
    "city": "Pittsburgh",
    "state": "Pennsylvania",
    "month": 5,
    "day": 25,
    "year": 2014,
    "analysis": {}
  },
  {
    "link": "http://www.datpiff.com/Mac-Miller-Macadelic-mixtape.327035.html",
    "thumb_image": "http://hw-img.datpiff.com/md375371/Mac_Miller_Macadelic-front.jpg",
    "title": "Macadelic",
    "artist": "Mac Miller",
    "downloads": 1206449,
    "city": "Pittsburgh",
    "state": "Pennsylvania",
    "month": 3,
    "day": 23,
    "year": 2012,
    "analysis": {}
  }
]
